alter table LIBRARY_BASE_TEST_ENTITY add constraint FK_LIBRARY_BASE_TEST_ENTITY_TOWN foreign key (TOWN_ID) references LIBRARY_TOWN(ID);
create index IDX_LIBRARY_BASE_TEST_ENTITY_TOWN on LIBRARY_BASE_TEST_ENTITY (TOWN_ID);
